version: '3'

services:

  backend: # GnS application
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_NAME: ${DB_NAME}
      DJANGO_DB_USER: ${DB_USER}
      DJANGO_DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 3306
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  db: # GnS database.
    image: mysql/mysql-server:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:

      - db:/var/lib/mysql

volumes:
  db: